package edu.udel.cisc675.randex;

/* Module FindAnswers: searches through the character array from the file,
   and for each problem, finds the starting and ending points of each answer.
   The answer includes "\item" and ends just before the next "\item" or
   "\end{enumerate}". */
public class FindAnswers {

    // strings we will search for...
    
    public final static char[] beginEnumerate =
	"\\begin{enumerate}".toCharArray();
    
    public final static char[] item = "\\item".toCharArray();
    
    public final static char[] endEnumerate =
	"\\end{enumerate}".toCharArray();

    /* The chars array generated by Input module (in) */
    char[] chars;

    /* Start index of each problem, from module FindProblems (in) */
    int[] probStarts;

    /* Stop index of each problem, from module FindProblems (in) */
    int[] probStops;

    /* For each problem i, start index of each answer to the problem
       (out).  This is an array of length number of problems.
       answerStarts[i] is an array whose length is the number of
       answers to the i-th problem.  answerStarts[i][j] is the index
       in chars of the first character of the j-th answer to the i-th
       problem. */
    int[][] answerStarts;

    /* Like answerStarts, except it gives the stop index of each
       answer (out).  That is 1 greater than the index of the last
       character of the answer. */
    int[][] answerStops;
    
    /* Constructs new FindAnswers instance from the given data.  Sets
       the fields and does nothing else. */
    public FindAnswers(char[] chars, int[] probStarts, int[] probStops) {
	this.chars = chars;
	this.probStarts = probStarts;
	this.probStops = probStops;
    }

    /* Constructs answerStarts and answerStops. */
    public void execute() {
	int nprob = probStarts.length;
	answerStarts = new int[nprob][];
	answerStops = new int[nprob][];
	FindAnswersInProblem findAnswersInProblem = new FindAnswersInProblem(chars, probStarts, probStops, answerStarts, answerStops);
	for (int i=0; i<nprob; i++)
	    findAnswersInProblem.findAnswersInProblem(i);
    }
}
